baseurl = "https://blog.pwne.rs/"
languageCode = "en-us"
title = "Pwners Blog"
theme = "hello-friend"
#copyright = ""
paginate = 5

[params]
  subtitle = "My Occasional Ramblings"
#  favicon = "/img/favicon.ico"
# [params.logo]
#   path = "/img/logo.png"
#   alt = "Pwners Blog"

#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about"
#  [[menu.main]]
#    identifier = "showcase"
#    name = "Showcase"
#    url = "/showcase"